### ISSUE TITLE
Question about how to run model?

### ISSUE THREAD

**Issue by HyejinWon** [fenneccat/NAVER_AIRUSH_Grammar_Error_Correction#1]
안녕하세요, ppt 흥미롭게 읽었습니다.

궁금한 점이 생겨서 연락드립니다.
1. 모델에 사용된 데이터는 공개가 어려울까요?
2. 모델을 돌리기 위해서는 어떻게 하면 될까요?
3. transformer를 사용했다고 하셨는데, 베이직 transformer 모델에 입력만 주신걸까요?

감사합니다!

**Comment by fenneccat** [comment]
제 자료를 읽어주셔서 감사합니다.

1. 일단, 이 태스크는 네이버에서 내부 데이터를 제공하여 네이버 내부 환경내에서 개발을 하였기 때문에 데이터 공개가 불가능합니다. 
2. 따라서 모델을 돌려보기는 다소 어려우실 것 같습니다. 유사한 한국어 교정 데이터가 있다면 모델 자체가 basic transformer기 때문에 다시 재 구현해서 사용해보실 수 있을 것 같습니다.
3. 네 맞습니다. 베이직 모델이라 그냥 트랜스포머모델을 사용하시면 될 것같고, 모델 성능 향상의 대부분은 데이터 생성과정과 pretraining에 있었기 때문에 적절한 데이터를 구하신다면 발표자료와 같이 구현하시면 될 것 같습니다.

감사합니다.
